WebProje/Models/ORM/Entity/BlogPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebProje.Models.ORM.Entity
{
    public class BlogPost : BaseEntity
    {
        [Display(Name ="Başlık")]
        public string Title { get; set; }

        public string Content { get; set; }

        public int CategoryID { get; set; }

        public string ImagePath { get; set; }

        [ForeignKey("CategoryID")]
        public virtual Category Category { get; set; }
    }
}

WebProje/Areas/Admin/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.Areas.Admin.Models.DTO;
using WebProje.Areas.Admin.Models.Services.HTMLDataSourceServices;
using WebProje.Models.ORM.Entity;

namespace WebProje.Areas.Admin.Controllers
{

    public class BlogPostController : BaseController
    {

        public ActionResult Index()
        {
            List<BlogPostVM> model = db.BlogPosts.Where(x => x.IsDeleted == false).OrderBy(x => x.AddDate).Select(x => new BlogPostVM()
            {
                Title = x.Title,
                CategoryName = x.Category.Name,
                ID = x.ID

            }).ToList();
            return View(model);
        }


        // GET: Admin/BlogPost
        public ActionResult AddBlogPost()
        {
            BlogPostVM model = new BlogPostVM();
            model.drpCategories = DrpServices.getDrpCategories();



            return View(model);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult AddBlogPost(BlogPostVM model)
        {
            BlogPostVM vmodel = new BlogPostVM();
            vmodel.drpCategories = DrpServices.getDrpCategories();

            if (ModelState.IsValid)
            {
                string filename = "";
                foreach (string name in Request.Files)
                {
                    
                    model.PostImage = Request.Files[name];
                    string ext = Path.GetExtension(Request.Files[name].FileName);

                    if (ext == ".jpg" || ext == ".jpeg" || ext == ".png")
                    {
                        string uniqimgnumber = Guid.NewGuid().ToString();
                        filename = uniqimgnumber + model.PostImage.FileName;

                        model.PostImage.SaveAs(Server.MapPath("~/Areas/Admin/Content/Site/images/blogpost/" + filename));
                    }
                    
                }

                BlogPost blogpost = new BlogPost();
                blogpost.CategoryID = model.CategoryID;
                blogpost.Title = model.Title;
                blogpost.Content = model.Content;
                blogpost.ImagePath = filename;

                db.BlogPosts.Add(blogpost);
                db.SaveChanges();
                ViewBag.IslemDurum = 1;
                return View(vmodel);

            }
            else
            {
                ViewBag.IslemDurum = 2;
                return View(vmodel);
            }

            
        }

        public ActionResult UpdateBlogPost(int id)
        {
            BlogPost blogpost = db.BlogPosts.FirstOrDefault(x => x.ID == id);
            BlogPostVM model = new BlogPostVM();
            model.CategoryID = blogpost.CategoryID;
            model.Title = blogpost.Title;
            model.Content = blogpost.Content;
            model.drpCategories = DrpServices.getDrpCategories();
            

            return View(model);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult UpdateBlogPost(BlogPostVM model)
        {
            model.drpCategories = DrpServices.getDrpCategories();
            if (ModelState.IsValid)
            {
                BlogPost blogpost = db.BlogPosts.FirstOrDefault(x => x.ID == model.ID);
                blogpost.CategoryID = model.CategoryID;
                blogpost.Title = model.Title;
                blogpost.Content = model.Content;

                db.SaveChanges();
                ViewBag.IslemDurum = 1;

                return View(model);
            }
            else
            {
                ViewBag.IslemDurum = 2;
                return View(model);
            }
                
        }

        public JsonResult DeleteBlogPost(int id)
        {
            BlogPost blogpost = db.BlogPosts.FirstOrDefault(x => x.ID == id);
            blogpost.IsDeleted = true;
            blogpost.DeleteDate = DateTime.Now;

            db.SaveChanges();

            return Json("");
        }
    }
}

WebProje/Areas/Admin/Views/BlogPost/AddBlogPost.cshtml
@{
    ViewBag.Title = "AddBlogPost";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Blog Yazısı Ekleme 
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">

    <div class="row">
        <!-- left column -->
        <div class="col-md-9">

            @Html.Partial("/Areas/Admin/Views/Shared/Partial/FormMessagesPartial.cshtml")

            <script src="~/Scripts/ckeditor/ckeditor.js"></script>
            <div class="box box-primary">

                @using (Html.BeginForm("AddBlogPost", "BlogPost", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/BlogPostForm")
  
                }
             </div>
        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>

WebProje/Areas/Admin/Views/BlogPost/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

@model List<WebProje.Areas.Admin.Models.DTO.BlogPostVM>

<link href="~/Areas/Admin/Content/css/dataTables.bootstrap.min.css" rel="stylesheet" />

<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTables.bootstrap.min.js"></script>
<script src="~/Scripts/custom/deleteRecordTable.js"></script>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        İçerik Listesi
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Kategori Listesi</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Data Table With Full Features</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Kategori Adı</th>
                                <th>Başlık</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr id="a_@item.ID">
                                    <td>@item.ID</td>
                                    <td>@item.CategoryName</td>
                                    <td>@item.Title</td>
                                    <td>
                                        <div>
                                            <a class="btn btn-info" href="/Admin/BlogPost/UpdateBlogPost/@item.ID">Güncelle</a>
                                            <button type="button" class="btn btn-danger" onclick="Delete('/Admin/Blogpost/DeleteBlogPost/',@item.ID)">Sil</button>
                                        </div>
                                    </td>
                                </tr>
                            }

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Kategori Adı</th>
                                <th>Başlık</th>
                                <th>İşlemler</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>

WebProje/Areas/Admin/Views/BlogPost/UpdateBlogPost.cshtml
@{
    ViewBag.Title = "UpdateBlogPost";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}



<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Blog Yazısı Güncelleme
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">

    <div class="row">
        <!-- left column -->
        <div class="col-md-9">

            @Html.Partial("/Areas/Admin/Views/Shared/Partial/FormMessagesPartial.cshtml")

            <script src="~/Scripts/ckeditor/ckeditor.js"></script>
            <div class="box box-primary">

                @using (Html.BeginForm("UpdateBlogPost", "BlogPost", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/BlogPostForm")

                }
            </div>

            <!-- general form elements -->
            <!-- /.box -->
        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>